// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMd7JKCM8WFst4oQnF8axdNQKYJm8AlRw',
    appId: '1:594110114774:web:8d59766874d0df9064d277',
    messagingSenderId: '594110114774',
    projectId: 'flutterapp2-3bb3d',
    authDomain: 'flutterapp2-3bb3d.firebaseapp.com',
    databaseURL: 'https://flutterapp2-3bb3d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterapp2-3bb3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQvgn4mz8w2nDmtTgyZCwO7rWuhYP59Z4',
    appId: '1:594110114774:android:d888992d0747de7764d277',
    messagingSenderId: '594110114774',
    projectId: 'flutterapp2-3bb3d',
    databaseURL: 'https://flutterapp2-3bb3d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterapp2-3bb3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW-xxO25wBmfzfOF1HG1pjDN--KGF1iBE',
    appId: '1:594110114774:ios:371178888c07218664d277',
    messagingSenderId: '594110114774',
    projectId: 'flutterapp2-3bb3d',
    databaseURL: 'https://flutterapp2-3bb3d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterapp2-3bb3d.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW-xxO25wBmfzfOF1HG1pjDN--KGF1iBE',
    appId: '1:594110114774:ios:371178888c07218664d277',
    messagingSenderId: '594110114774',
    projectId: 'flutterapp2-3bb3d',
    databaseURL: 'https://flutterapp2-3bb3d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterapp2-3bb3d.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMd7JKCM8WFst4oQnF8axdNQKYJm8AlRw',
    appId: '1:594110114774:web:e54c1d2e00d24ba064d277',
    messagingSenderId: '594110114774',
    projectId: 'flutterapp2-3bb3d',
    authDomain: 'flutterapp2-3bb3d.firebaseapp.com',
    databaseURL: 'https://flutterapp2-3bb3d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterapp2-3bb3d.firebasestorage.app',
  );
}
